components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: FastAPI
  version: 0.1.0
openapi: 3.1.0
paths:
  /:
    get:
      operationId: read_root__get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Read Root
  /v1/spaces/{user_id}/note/{note_id}:
    delete:
      operationId: delete_note_v1_spaces__user_id__note__note_id__delete
      parameters:
      - in: path
        name: user_id
        required: true
        schema:
          format: uuid
          title: User Id
          type: string
      - in: path
        name: note_id
        required: true
        schema:
          format: uuid
          title: Note Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Delete Note
    put:
      operationId: update_note_v1_spaces__user_id__note__note_id__put
      parameters:
      - in: path
        name: user_id
        required: true
        schema:
          format: uuid
          title: User Id
          type: string
      - in: path
        name: note_id
        required: true
        schema:
          format: uuid
          title: Note Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              title: Note
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Update Note
  /v1/spaces/{user_id}/pdf/{pdf_id}:
    delete:
      operationId: delete_pdf_v1_spaces__user_id__pdf__pdf_id__delete
      parameters:
      - in: path
        name: user_id
        required: true
        schema:
          format: uuid
          title: User Id
          type: string
      - in: path
        name: pdf_id
        required: true
        schema:
          format: uuid
          title: Pdf Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Delete Pdf
    put:
      operationId: update_pdf_v1_spaces__user_id__pdf__pdf_id__put
      parameters:
      - in: path
        name: user_id
        required: true
        schema:
          format: uuid
          title: User Id
          type: string
      - in: path
        name: pdf_id
        required: true
        schema:
          format: uuid
          title: Pdf Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              title: Pdf
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Update Pdf
  /v1/spaces/{user_id}/webContent/{web_content_id}:
    delete:
      operationId: delete_web_content_v1_spaces__user_id__webContent__web_content_id__delete
      parameters:
      - in: path
        name: user_id
        required: true
        schema:
          format: uuid
          title: User Id
          type: string
      - in: path
        name: web_content_id
        required: true
        schema:
          format: uuid
          title: Web Content Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Delete Web Content
    put:
      operationId: update_web_content_v1_spaces__user_id__webContent__web_content_id__put
      parameters:
      - in: path
        name: user_id
        required: true
        schema:
          format: uuid
          title: User Id
          type: string
      - in: path
        name: web_content_id
        required: true
        schema:
          format: uuid
          title: Web Content Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              title: Web Content
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Update Web Content
